name: Python Flake8 Lint

on: pull_request

jobs:
  flake8:
    name: Lint Python
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install flake8
        run: pip install flake8

      - name: Get changed Python files
        id: files
        run: |
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} | grep '\.py$' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        shell: bash

      - name: Run flake8 on changed files
        run: |
          if [ -s $CHANGED_FILES ]; then
            flake8 --output-file=flake8_report.txt $(cat $CHANGED_FILES)
            if [ $? -ne 0 ]; then
              echo "Flake8 style errors:"
              cat flake8_report.txt
              exit 1
            fi
          else
            echo "No Python files changed."
          fi
        shell: bash
