name: Flake8 Code Style Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  flake8-style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Adjust the Python version as needed

      - name: Install flake8
        run: pip install flake8

      - name: Get list of changed Python files
        id: files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} | grep '\.py$')
          echo "::set-output name=python_files::$CHANGED_FILES"

      - name: Check Python files with flake8
        if: steps.files.outputs.python_files != ''
        run: flake8 ${{ steps.files.outputs.python_files }} --ignore E501
        continue-on-error: true  # Optionally set this to false to fail the job on any error

