name: Python Flake8 Lint

on: pull_request

jobs:
  flake8:
    name: Lint Python
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8 and capture output
        run: |
          set -xe
          git fetch --all
          git branch -r
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- '*.py')
          if [ -z "$CHANGED_FILES" ]; then
            echo "No Python files changed."
          else
            flake8 $CHANGED_FILES --ignore E501 --output-file flake8_report.txt || true
          fi
        shell: bash

      - name: Run reviewdog
        uses: reviewdog/action-setup@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          tool_name: flake8
          filter_mode: added
          fail_on_error: true
          level: error
          report_only_modified_lines: true
          flag_nolabel: true
          workdir: .
          path: "flake8_report.txt"

