name: Flake8 Code Style Check

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]

jobs:
  flake8-style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Adjust the Python version as needed

      - name: Install flake8
        run: pip install flake8

      - name: Get list of changed Python files
        id: files
        run: |
          FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.py$' || true)
          echo "::set-output name=python_files::$FILES"

      - name: Check Python files with flake8
        if: steps.files.outputs.python_files != ''
        run: flake8 ${{ steps.files.outputs.python_files }} --ignore E501
        continue-on-error: true  # Optionally set this to false to fail the job on any error
