name: Python Flake8 Lint

on: pull_request

jobs:
  flake8:
    name: Lint Python
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8 on changed Python files
        run: |
          set -xe
          echo "Fetching list of changed Python files..."
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.py$' || true)
          if [ -z "$CHANGED_FILES" ]; then
            echo "No Python files changed."
          else
            echo "Running flake8 on changed files:"
            echo $CHANGED_FILES
            flake8 $CHANGED_FILES
            if [ $? -ne 0 ]; then
              echo "Flake8 found issues in the following files:"
              echo $CHANGED_FILES
              exit 1
            fi
          fi
        shell: bash
