name: flake8 Lint

on:
  pull_request:
    types: [review_requested]
    branches: [main]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - run: pip install flake8
      - run: pip install flake8-docstrings flake8-simplify flake8-unused-arguments flake8-quotes
      - name: flake8 Lint
        uses: reviewdog/action-flake8@v3
        with:
          reporter: github-pr-review
          filter_mode: diff_context
          fail_on_error: true
          level: info
          flake8_args: --ignore E501
          github_token: ${{ secrets.GITHUB_TOKEN }}
